name: simple-WGAN
dependencies:
  - python=3.7.4
  - pytorch::pytorch=1.4.0
  - pytorch::torchvision=0.5.0
  - cudatoolkit
  - scipy=1.4.1
  - matplotlib 
  - pandas=1.0.5
  - pip=20.1.1
  - pip:
    - opencv-python